/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as ConsultancyRouteImport } from './routes/consultancy'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagementIndexRouteImport } from './routes/management/index'
import { Route as ConsultancyIndexRouteImport } from './routes/consultancy/index'
import { Route as CapitalIndexRouteImport } from './routes/capital/index'
import { Route as ManagementPortfolioRouteImport } from './routes/management/portfolio'
import { Route as ManagementContactRouteImport } from './routes/management/contact'
import { Route as ManagementAuraAnimaliaRouteImport } from './routes/management/aura-animalia'
import { Route as ManagementAboutRouteImport } from './routes/management/about'
import { Route as ConsultancyServicesRouteImport } from './routes/consultancy/services'
import { Route as ConsultancyContactRouteImport } from './routes/consultancy/contact'
import { Route as ConsultancyAboutRouteImport } from './routes/consultancy/about'
import { Route as CapitalServicesRouteImport } from './routes/capital/services'
import { Route as CapitalContactRouteImport } from './routes/capital/contact'
import { Route as CapitalAboutRouteImport } from './routes/capital/about'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyRoute = ConsultancyRouteImport.update({
  id: '/consultancy',
  path: '/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementRoute,
} as any)
const ConsultancyIndexRoute = ConsultancyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultancyRoute,
} as any)
const CapitalIndexRoute = CapitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CapitalRoute,
} as any)
const ManagementPortfolioRoute = ManagementPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementContactRoute = ManagementContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementAuraAnimaliaRoute = ManagementAuraAnimaliaRouteImport.update({
  id: '/aura-animalia',
  path: '/aura-animalia',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementAboutRoute = ManagementAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ManagementRoute,
} as any)
const ConsultancyServicesRoute = ConsultancyServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ConsultancyRoute,
} as any)
const ConsultancyContactRoute = ConsultancyContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ConsultancyRoute,
} as any)
const ConsultancyAboutRoute = ConsultancyAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ConsultancyRoute,
} as any)
const CapitalServicesRoute = CapitalServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => CapitalRoute,
} as any)
const CapitalContactRoute = CapitalContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CapitalRoute,
} as any)
const CapitalAboutRoute = CapitalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => CapitalRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capital': typeof CapitalRouteWithChildren
  '/consultancy': typeof ConsultancyRouteWithChildren
  '/management': typeof ManagementRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/capital/about': typeof CapitalAboutRoute
  '/capital/contact': typeof CapitalContactRoute
  '/capital/services': typeof CapitalServicesRoute
  '/consultancy/about': typeof ConsultancyAboutRoute
  '/consultancy/contact': typeof ConsultancyContactRoute
  '/consultancy/services': typeof ConsultancyServicesRoute
  '/management/about': typeof ManagementAboutRoute
  '/management/aura-animalia': typeof ManagementAuraAnimaliaRoute
  '/management/contact': typeof ManagementContactRoute
  '/management/portfolio': typeof ManagementPortfolioRoute
  '/capital/': typeof CapitalIndexRoute
  '/consultancy/': typeof ConsultancyIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/capital/about': typeof CapitalAboutRoute
  '/capital/contact': typeof CapitalContactRoute
  '/capital/services': typeof CapitalServicesRoute
  '/consultancy/about': typeof ConsultancyAboutRoute
  '/consultancy/contact': typeof ConsultancyContactRoute
  '/consultancy/services': typeof ConsultancyServicesRoute
  '/management/about': typeof ManagementAboutRoute
  '/management/aura-animalia': typeof ManagementAuraAnimaliaRoute
  '/management/contact': typeof ManagementContactRoute
  '/management/portfolio': typeof ManagementPortfolioRoute
  '/capital': typeof CapitalIndexRoute
  '/consultancy': typeof ConsultancyIndexRoute
  '/management': typeof ManagementIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capital': typeof CapitalRouteWithChildren
  '/consultancy': typeof ConsultancyRouteWithChildren
  '/management': typeof ManagementRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/capital/about': typeof CapitalAboutRoute
  '/capital/contact': typeof CapitalContactRoute
  '/capital/services': typeof CapitalServicesRoute
  '/consultancy/about': typeof ConsultancyAboutRoute
  '/consultancy/contact': typeof ConsultancyContactRoute
  '/consultancy/services': typeof ConsultancyServicesRoute
  '/management/about': typeof ManagementAboutRoute
  '/management/aura-animalia': typeof ManagementAuraAnimaliaRoute
  '/management/contact': typeof ManagementContactRoute
  '/management/portfolio': typeof ManagementPortfolioRoute
  '/capital/': typeof CapitalIndexRoute
  '/consultancy/': typeof ConsultancyIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capital'
    | '/consultancy'
    | '/management'
    | '/api/$'
    | '/capital/about'
    | '/capital/contact'
    | '/capital/services'
    | '/consultancy/about'
    | '/consultancy/contact'
    | '/consultancy/services'
    | '/management/about'
    | '/management/aura-animalia'
    | '/management/contact'
    | '/management/portfolio'
    | '/capital/'
    | '/consultancy/'
    | '/management/'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/capital/about'
    | '/capital/contact'
    | '/capital/services'
    | '/consultancy/about'
    | '/consultancy/contact'
    | '/consultancy/services'
    | '/management/about'
    | '/management/aura-animalia'
    | '/management/contact'
    | '/management/portfolio'
    | '/capital'
    | '/consultancy'
    | '/management'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/capital'
    | '/consultancy'
    | '/management'
    | '/api/$'
    | '/capital/about'
    | '/capital/contact'
    | '/capital/services'
    | '/consultancy/about'
    | '/consultancy/contact'
    | '/consultancy/services'
    | '/management/about'
    | '/management/aura-animalia'
    | '/management/contact'
    | '/management/portfolio'
    | '/capital/'
    | '/consultancy/'
    | '/management/'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapitalRoute: typeof CapitalRouteWithChildren
  ConsultancyRoute: typeof ConsultancyRouteWithChildren
  ManagementRoute: typeof ManagementRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy': {
      id: '/consultancy'
      path: '/consultancy'
      fullPath: '/consultancy'
      preLoaderRoute: typeof ConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/': {
      id: '/management/'
      path: '/'
      fullPath: '/management/'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/consultancy/': {
      id: '/consultancy/'
      path: '/'
      fullPath: '/consultancy/'
      preLoaderRoute: typeof ConsultancyIndexRouteImport
      parentRoute: typeof ConsultancyRoute
    }
    '/capital/': {
      id: '/capital/'
      path: '/'
      fullPath: '/capital/'
      preLoaderRoute: typeof CapitalIndexRouteImport
      parentRoute: typeof CapitalRoute
    }
    '/management/portfolio': {
      id: '/management/portfolio'
      path: '/portfolio'
      fullPath: '/management/portfolio'
      preLoaderRoute: typeof ManagementPortfolioRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/contact': {
      id: '/management/contact'
      path: '/contact'
      fullPath: '/management/contact'
      preLoaderRoute: typeof ManagementContactRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/aura-animalia': {
      id: '/management/aura-animalia'
      path: '/aura-animalia'
      fullPath: '/management/aura-animalia'
      preLoaderRoute: typeof ManagementAuraAnimaliaRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/about': {
      id: '/management/about'
      path: '/about'
      fullPath: '/management/about'
      preLoaderRoute: typeof ManagementAboutRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/consultancy/services': {
      id: '/consultancy/services'
      path: '/services'
      fullPath: '/consultancy/services'
      preLoaderRoute: typeof ConsultancyServicesRouteImport
      parentRoute: typeof ConsultancyRoute
    }
    '/consultancy/contact': {
      id: '/consultancy/contact'
      path: '/contact'
      fullPath: '/consultancy/contact'
      preLoaderRoute: typeof ConsultancyContactRouteImport
      parentRoute: typeof ConsultancyRoute
    }
    '/consultancy/about': {
      id: '/consultancy/about'
      path: '/about'
      fullPath: '/consultancy/about'
      preLoaderRoute: typeof ConsultancyAboutRouteImport
      parentRoute: typeof ConsultancyRoute
    }
    '/capital/services': {
      id: '/capital/services'
      path: '/services'
      fullPath: '/capital/services'
      preLoaderRoute: typeof CapitalServicesRouteImport
      parentRoute: typeof CapitalRoute
    }
    '/capital/contact': {
      id: '/capital/contact'
      path: '/contact'
      fullPath: '/capital/contact'
      preLoaderRoute: typeof CapitalContactRouteImport
      parentRoute: typeof CapitalRoute
    }
    '/capital/about': {
      id: '/capital/about'
      path: '/about'
      fullPath: '/capital/about'
      preLoaderRoute: typeof CapitalAboutRouteImport
      parentRoute: typeof CapitalRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CapitalRouteChildren {
  CapitalAboutRoute: typeof CapitalAboutRoute
  CapitalContactRoute: typeof CapitalContactRoute
  CapitalServicesRoute: typeof CapitalServicesRoute
  CapitalIndexRoute: typeof CapitalIndexRoute
}

const CapitalRouteChildren: CapitalRouteChildren = {
  CapitalAboutRoute: CapitalAboutRoute,
  CapitalContactRoute: CapitalContactRoute,
  CapitalServicesRoute: CapitalServicesRoute,
  CapitalIndexRoute: CapitalIndexRoute,
}

const CapitalRouteWithChildren =
  CapitalRoute._addFileChildren(CapitalRouteChildren)

interface ConsultancyRouteChildren {
  ConsultancyAboutRoute: typeof ConsultancyAboutRoute
  ConsultancyContactRoute: typeof ConsultancyContactRoute
  ConsultancyServicesRoute: typeof ConsultancyServicesRoute
  ConsultancyIndexRoute: typeof ConsultancyIndexRoute
}

const ConsultancyRouteChildren: ConsultancyRouteChildren = {
  ConsultancyAboutRoute: ConsultancyAboutRoute,
  ConsultancyContactRoute: ConsultancyContactRoute,
  ConsultancyServicesRoute: ConsultancyServicesRoute,
  ConsultancyIndexRoute: ConsultancyIndexRoute,
}

const ConsultancyRouteWithChildren = ConsultancyRoute._addFileChildren(
  ConsultancyRouteChildren,
)

interface ManagementRouteChildren {
  ManagementAboutRoute: typeof ManagementAboutRoute
  ManagementAuraAnimaliaRoute: typeof ManagementAuraAnimaliaRoute
  ManagementContactRoute: typeof ManagementContactRoute
  ManagementPortfolioRoute: typeof ManagementPortfolioRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
}

const ManagementRouteChildren: ManagementRouteChildren = {
  ManagementAboutRoute: ManagementAboutRoute,
  ManagementAuraAnimaliaRoute: ManagementAuraAnimaliaRoute,
  ManagementContactRoute: ManagementContactRoute,
  ManagementPortfolioRoute: ManagementPortfolioRoute,
  ManagementIndexRoute: ManagementIndexRoute,
}

const ManagementRouteWithChildren = ManagementRoute._addFileChildren(
  ManagementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapitalRoute: CapitalRouteWithChildren,
  ConsultancyRoute: ConsultancyRouteWithChildren,
  ManagementRoute: ManagementRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
